import { drizzle } from "drizzle-orm/mysql2";
import { protocols } from "../drizzle/schema";
import type { InsertProtocol } from "../drizzle/schema";

const db = drizzle(process.env.DATABASE_URL!);

const protocolData: InsertProtocol[] = [
  // ─── STAGE 1: Fear & Avoidance (18+ → 12-15 bpm) ───────────────────────
  {
    name: "Root Lock",
    slug: "root-lock",
    stageRequired: 1,
    chakraFocus: ["root"],
    element: "earth",
    durationMinutes: 5,
    targetBreathRate: 12,
    difficulty: "beginner",
    description: "Ground yourself. Activate the Root chakra to suppress pre-fight fear and stabilize stance. This is your foundation protocol.",
    steps: [
      "Sit or stand in a stable position. Feet shoulder-width apart.",
      "Engage sphincter lock (Mula Bandha) — contract and hold.",
      "Press tongue firmly to roof of mouth.",
      "Inhale deeply through nose, expanding belly outward.",
      "Sound AHHH on exhale — feel it resonate in your root.",
      "Follow with Shhh detox breath — sharp exhale through teeth.",
      "Repeat for full duration. Maintain lock throughout.",
    ],
    inhaleSeconds: 4,
    holdAfterInhaleSeconds: 1,
    exhaleSeconds: 5,
    holdAfterExhaleSeconds: 0,
    soundFrequency: "396hz",
    chakraSoundSyllable: "AHHH",
    tags: ["grounding", "fear-suppression", "stability"],
    isFreeAccess: true,
    sortOrder: 1,
  },
  {
    name: "Fear Override",
    slug: "fear-override",
    stageRequired: 1,
    chakraFocus: ["solar-plexus"],
    element: "fire",
    durationMinutes: 4,
    targetBreathRate: 14,
    difficulty: "beginner",
    description: "Override the fear response with Solar Plexus fire. Converts anxiety into controlled aggression.",
    steps: [
      "Stand in fighting stance. Hands loose at sides.",
      "Expand diaphragm fully — push belly down and out.",
      "Inhale through nose, feel core activate.",
      "Sound Youuuu on exhale — from deep in the solar plexus.",
      "Hold for 30 seconds at peak tension.",
      "Release with Sssss detox — hissing exhale.",
      "Repeat cycle. Feel fear transmute to power.",
    ],
    inhaleSeconds: 4,
    holdAfterInhaleSeconds: 2,
    exhaleSeconds: 4,
    holdAfterExhaleSeconds: 0,
    soundFrequency: "528hz",
    chakraSoundSyllable: "Youuuu",
    tags: ["fear-override", "aggression-control", "core-power"],
    isFreeAccess: false,
    sortOrder: 2,
  },
  {
    name: "Ground Zero",
    slug: "ground-zero",
    stageRequired: 1,
    chakraFocus: ["root", "heart"],
    element: "earth",
    durationMinutes: 5,
    targetBreathRate: 12,
    difficulty: "beginner",
    description: "Dual-chakra activation connecting Root stability to Heart courage. The foundation of emotional regulation in combat.",
    steps: [
      "Sit in full lotus or cross-legged if possible.",
      "Begin with AHHH sound — Root activation.",
      "Transition to SoLLLL — Heart activation.",
      "Cycle between both sounds with each breath.",
      "Apply belly lock on each inhale.",
      "Exhale with 8-second massage breath — slow, controlled.",
      "Feel the connection between ground and heart.",
    ],
    inhaleSeconds: 4,
    holdAfterInhaleSeconds: 0,
    exhaleSeconds: 8,
    holdAfterExhaleSeconds: 0,
    soundFrequency: "396hz",
    chakraSoundSyllable: "AHHH",
    tags: ["dual-chakra", "emotional-regulation", "courage"],
    isFreeAccess: false,
    sortOrder: 3,
  },
  {
    name: "Stance Anchor",
    slug: "stance-anchor",
    stageRequired: 1,
    chakraFocus: ["root"],
    element: "earth",
    durationMinutes: 3,
    targetBreathRate: 15,
    difficulty: "beginner",
    description: "Quick-activation protocol for pre-training grounding. Anchors your stance and clears mental noise in under 3 minutes.",
    steps: [
      "Stand in your fighting stance. Eyes forward.",
      "Three deep belly breaths — no sound, just feel.",
      "On fourth breath: AHHH exhale, full root engagement.",
      "Repeat 10 cycles with increasing intensity.",
      "End with 5-second hold at full root lock.",
      "Release. Feel the ground beneath you.",
    ],
    inhaleSeconds: 3,
    holdAfterInhaleSeconds: 0,
    exhaleSeconds: 4,
    holdAfterExhaleSeconds: 1,
    soundFrequency: "396hz",
    chakraSoundSyllable: "AHHH",
    tags: ["quick-activation", "pre-training", "grounding"],
    isFreeAccess: false,
    sortOrder: 4,
  },
  {
    name: "Hip Flow",
    slug: "hip-flow",
    stageRequired: 1,
    chakraFocus: ["sacral"],
    element: "water",
    durationMinutes: 4,
    targetBreathRate: 13,
    difficulty: "beginner",
    description: "Sacral chakra activation for hip fluidity and movement adaptation. Essential for grapplers and strikers.",
    steps: [
      "Stand with feet wide. Begin slow hip circles.",
      "Sync breath with movement — inhale on open, exhale on close.",
      "Sound Oooo on exhale — feel it in the hips.",
      "Increase circle size with each breath cycle.",
      "Add lateral hip shifts — left, right, forward, back.",
      "End with 10 rapid Oooo pulses.",
    ],
    inhaleSeconds: 4,
    holdAfterInhaleSeconds: 0,
    exhaleSeconds: 4,
    holdAfterExhaleSeconds: 0,
    soundFrequency: "417hz",
    chakraSoundSyllable: "Oooo",
    tags: ["hip-mobility", "fluidity", "adaptation"],
    isFreeAccess: false,
    sortOrder: 5,
  },
  {
    name: "Iron Will",
    slug: "iron-will",
    stageRequired: 1,
    chakraFocus: ["solar-plexus"],
    element: "fire",
    durationMinutes: 5,
    targetBreathRate: 14,
    difficulty: "beginner",
    description: "Build unbreakable will through Solar Plexus fire breathing. Converts hesitation into decisive action.",
    steps: [
      "Stand tall. Chest out. Chin level.",
      "Place both hands on solar plexus.",
      "Inhale — feel hands rise with belly expansion.",
      "Youuuu exhale — push hands inward, feel the fire.",
      "Increase intensity each round.",
      "Final round: maximum force on Youuuu, 10 reps.",
      "Finish with 3 power exhales — no sound, pure force.",
    ],
    inhaleSeconds: 4,
    holdAfterInhaleSeconds: 1,
    exhaleSeconds: 4,
    holdAfterExhaleSeconds: 0,
    soundFrequency: "528hz",
    chakraSoundSyllable: "Youuuu",
    tags: ["willpower", "decisive-action", "fire"],
    isFreeAccess: false,
    sortOrder: 6,
  },

  // ─── STAGE 2: Addiction & Rush (12-18 → 8-12 bpm) ──────────────────────
  {
    name: "Rush Kill",
    slug: "rush-kill",
    stageRequired: 2,
    chakraFocus: ["throat"],
    element: "air",
    durationMinutes: 6,
    targetBreathRate: 10,
    difficulty: "intermediate",
    description: "Kill the adrenaline addiction. Throat chakra regulation to remove the need for the rush and build sustainable rhythm.",
    steps: [
      "Sit in silence. Remove all external sound sources.",
      "Nostril breathing only — mouth sealed.",
      "Sound Eeeee on exhale — feel throat vibrate.",
      "Establish 4-4-4-4 box breathing pattern.",
      "When urge to rush arises — slow down further.",
      "Maintain rhythm for full 6 minutes.",
      "No music. No distractions. Face the silence.",
    ],
    inhaleSeconds: 4,
    holdAfterInhaleSeconds: 4,
    exhaleSeconds: 4,
    holdAfterExhaleSeconds: 4,
    soundFrequency: "741hz",
    chakraSoundSyllable: "Eeeee",
    tags: ["rhythm", "consistency", "throat-regulation"],
    isFreeAccess: true,
    sortOrder: 7,
  },
  {
    name: "Addict Detox",
    slug: "addict-detox",
    stageRequired: 2,
    chakraFocus: ["third-eye"],
    element: "water",
    durationMinutes: 8,
    targetBreathRate: 8,
    difficulty: "intermediate",
    description: "Third Eye protocol to break the pattern-seeking addiction. Face the silence and stop chasing altered states.",
    steps: [
      "Sit in complete silence. No music.",
      "Close eyes. Focus on the space between thoughts.",
      "Sound SONNN on exhale — feel it in the forehead.",
      "Hold for 15 seconds after each exhale.",
      "When mind wanders to the rush — return to SONNN.",
      "Do not chase. Do not resist. Simply breathe.",
      "Complete all 8 minutes without breaking rhythm.",
    ],
    inhaleSeconds: 5,
    holdAfterInhaleSeconds: 2,
    exhaleSeconds: 8,
    holdAfterExhaleSeconds: 15,
    soundFrequency: "852hz",
    chakraSoundSyllable: "SONNN",
    tags: ["pattern-breaking", "silence", "detox"],
    isFreeAccess: false,
    sortOrder: 8,
  },
  {
    name: "Pattern Break",
    slug: "pattern-break",
    stageRequired: 2,
    chakraFocus: ["crown"],
    element: "air",
    durationMinutes: 7,
    targetBreathRate: 9,
    difficulty: "intermediate",
    description: "Crown chakra reset to break addictive breathing patterns. SAUMMM sound for total awareness recalibration.",
    steps: [
      "Sit upright. Spine straight. No support.",
      "Begin SAUMMM sound — let it fill the crown.",
      "Slow inhale: 4 seconds through nose.",
      "Hold: 4 seconds — feel the crown expand.",
      "Exhale: 6 seconds — SAUMMM throughout.",
      "No distractions. No phone. No music.",
      "Repeat for full 7 minutes.",
    ],
    inhaleSeconds: 4,
    holdAfterInhaleSeconds: 4,
    exhaleSeconds: 6,
    holdAfterExhaleSeconds: 0,
    soundFrequency: "963hz",
    chakraSoundSyllable: "SAUMMM",
    tags: ["crown-reset", "awareness", "pattern-break"],
    isFreeAccess: false,
    sortOrder: 9,
  },
  {
    name: "Sacral Release",
    slug: "sacral-release",
    stageRequired: 2,
    chakraFocus: ["sacral"],
    element: "water",
    durationMinutes: 6,
    targetBreathRate: 10,
    difficulty: "intermediate",
    description: "Release emotional blockages stored in the Sacral chakra. Fluid breathing for fluid movement.",
    steps: [
      "Lie on back or sit cross-legged.",
      "Place hands on lower abdomen — sacral region.",
      "Inhale: feel hands rise, Oooo on exhale.",
      "Imagine water flowing through the pelvis.",
      "Release tension with each exhale.",
      "Add gentle rocking motion after minute 3.",
      "End with 5 deep release breaths.",
    ],
    inhaleSeconds: 5,
    holdAfterInhaleSeconds: 0,
    exhaleSeconds: 6,
    holdAfterExhaleSeconds: 2,
    soundFrequency: "417hz",
    chakraSoundSyllable: "Oooo",
    tags: ["emotional-release", "fluidity", "sacral"],
    isFreeAccess: false,
    sortOrder: 10,
  },
  {
    name: "Heart Armor",
    slug: "heart-armor",
    stageRequired: 2,
    chakraFocus: ["heart"],
    element: "water",
    durationMinutes: 7,
    targetBreathRate: 9,
    difficulty: "intermediate",
    description: "Build emotional armor through Heart chakra activation. Courage without recklessness. Presence without fear.",
    steps: [
      "Sit with hands on heart center.",
      "Begin SoLLLL sound — feel chest resonate.",
      "Inhale: expand chest fully, feel heart open.",
      "Exhale: SoLLLL — let emotion move through, not stay.",
      "After 3 minutes: increase sound intensity.",
      "Feel the difference between armor and wall.",
      "End with 3 silent breaths — pure presence.",
    ],
    inhaleSeconds: 5,
    holdAfterInhaleSeconds: 1,
    exhaleSeconds: 6,
    holdAfterExhaleSeconds: 0,
    soundFrequency: "639hz",
    chakraSoundSyllable: "SoLLLL",
    tags: ["courage", "emotional-armor", "presence"],
    isFreeAccess: false,
    sortOrder: 11,
  },
  {
    name: "Throat Command",
    slug: "throat-command",
    stageRequired: 2,
    chakraFocus: ["throat"],
    element: "air",
    durationMinutes: 5,
    targetBreathRate: 11,
    difficulty: "intermediate",
    description: "Throat chakra for breath projection and vocal power. Command your breath, command the fight.",
    steps: [
      "Stand or sit upright. Throat relaxed.",
      "Begin with 3 loud Eeeee sounds — feel the vibration.",
      "Transition to controlled Eeeee on every exhale.",
      "Increase projection — feel sound travel forward.",
      "Add breath holds after each Eeeee: 3 seconds.",
      "Final 2 minutes: maximum resonance, minimum effort.",
    ],
    inhaleSeconds: 4,
    holdAfterInhaleSeconds: 0,
    exhaleSeconds: 5,
    holdAfterExhaleSeconds: 3,
    soundFrequency: "741hz",
    chakraSoundSyllable: "Eeeee",
    tags: ["vocal-power", "projection", "command"],
    isFreeAccess: false,
    sortOrder: 12,
  },

  // ─── STAGE 3: Rhythm & Presence (8-12 → 6-8 bpm) ───────────────────────
  {
    name: "Between Rounds",
    slug: "between-rounds",
    stageRequired: 3,
    chakraFocus: ["solar-plexus", "heart"],
    element: "fire",
    durationMinutes: 10,
    targetBreathRate: 6,
    difficulty: "advanced",
    description: "The cornerstone Stage 3 protocol. Dual Fire-Water activation for controlled aggression and sustainable output between rounds.",
    steps: [
      "Apply full lock sequence: sphincter, tongue, belly.",
      "Begin 15-second holds after each inhale.",
      "Cycle through all 7 sounds: AHHH → Oooo → Youuuu → SoLLLL → Eeeee → SONNN → SAUMMM.",
      "3 complete cycles minimum.",
      "Add nostril variations: alternate nostril for last 3 minutes.",
      "Breath is your compass — let it guide intensity.",
      "Do not force. Do not rush. The rhythm is the weapon.",
    ],
    inhaleSeconds: 5,
    holdAfterInhaleSeconds: 15,
    exhaleSeconds: 8,
    holdAfterExhaleSeconds: 2,
    soundFrequency: "528hz",
    chakraSoundSyllable: "Youuuu",
    tags: ["between-rounds", "dual-chakra", "rhythm"],
    isFreeAccess: true,
    sortOrder: 13,
  },
  {
    name: "Pre-Fight Stack",
    slug: "pre-fight-stack",
    stageRequired: 3,
    chakraFocus: ["root", "sacral", "solar-plexus", "heart", "throat", "third-eye", "crown"],
    element: "fire",
    durationMinutes: 15,
    targetBreathRate: 6,
    difficulty: "advanced",
    description: "Full 7-chakra activation sequence for pre-competition preparation. All elements, all chakras, complete energetic alignment.",
    steps: [
      "Complete AHHH to SAUMMM cycling — all 7 chakras.",
      "6 Shhh detox breaths + 6 Sssss detox breaths.",
      "Elemental balance sequence: Earth → Water → Fire → Air.",
      "Each element: 3 breath cycles minimum.",
      "Final 3 minutes: all chakras simultaneously.",
      "End in silence — feel the stack complete.",
    ],
    inhaleSeconds: 5,
    holdAfterInhaleSeconds: 5,
    exhaleSeconds: 8,
    holdAfterExhaleSeconds: 2,
    soundFrequency: "528hz",
    chakraSoundSyllable: "SAUMMM",
    tags: ["pre-fight", "full-stack", "all-chakras"],
    isFreeAccess: false,
    sortOrder: 14,
  },
  {
    name: "Recovery Field",
    slug: "recovery-field",
    stageRequired: 3,
    chakraFocus: ["heart", "throat"],
    element: "water",
    durationMinutes: 12,
    targetBreathRate: 7,
    difficulty: "advanced",
    description: "Post-training recovery protocol. Heart-Throat activation for emotional processing and circadian rhythm alignment.",
    steps: [
      "Lie down or sit in full recline.",
      "Begin SoLLLL — Heart activation.",
      "Transition to Eeeee — Throat release.",
      "Alternate between both sounds every 2 minutes.",
      "Process any emotions from training — let them move.",
      "Align breath with natural circadian rhythm.",
      "End with 5 minutes of silent, natural breathing.",
    ],
    inhaleSeconds: 6,
    holdAfterInhaleSeconds: 2,
    exhaleSeconds: 8,
    holdAfterExhaleSeconds: 0,
    soundFrequency: "639hz",
    chakraSoundSyllable: "SoLLLL",
    tags: ["recovery", "emotional-processing", "circadian"],
    isFreeAccess: false,
    sortOrder: 15,
  },
  {
    name: "Third Eye Strike",
    slug: "third-eye-strike",
    stageRequired: 3,
    chakraFocus: ["third-eye"],
    element: "air",
    durationMinutes: 10,
    targetBreathRate: 6,
    difficulty: "advanced",
    description: "Third Eye activation for pattern recognition and combat intuition. See the fight before it happens.",
    steps: [
      "Sit in darkness or with eyes closed.",
      "Focus attention on the space between eyebrows.",
      "SONNN sound — feel it vibrate in the skull.",
      "With each exhale: visualize opponent patterns.",
      "After 5 minutes: hold breath for 20 seconds.",
      "On release: SONNN with maximum intensity.",
      "Final 2 minutes: pure silence, pure vision.",
    ],
    inhaleSeconds: 5,
    holdAfterInhaleSeconds: 20,
    exhaleSeconds: 8,
    holdAfterExhaleSeconds: 0,
    soundFrequency: "852hz",
    chakraSoundSyllable: "SONNN",
    tags: ["intuition", "pattern-recognition", "vision"],
    isFreeAccess: false,
    sortOrder: 16,
  },
  {
    name: "Pressure Test",
    slug: "pressure-test",
    stageRequired: 3,
    chakraFocus: ["solar-plexus", "root"],
    element: "earth",
    durationMinutes: 12,
    targetBreathRate: 7,
    difficulty: "advanced",
    description: "Simulate high-pressure scenarios through breath. Build the ability to maintain rhythm when everything says panic.",
    steps: [
      "Begin at normal pace — establish rhythm first.",
      "Minute 3: introduce 10-second holds mid-exhale.",
      "Minute 6: add Youuuu sound at maximum volume.",
      "Minute 8: reduce to 4 breaths per minute.",
      "Minute 10: hold for 25 seconds — do not break.",
      "Release: AHHH — feel the pressure dissolve.",
      "Final 2 minutes: return to baseline rhythm.",
    ],
    inhaleSeconds: 5,
    holdAfterInhaleSeconds: 10,
    exhaleSeconds: 8,
    holdAfterExhaleSeconds: 2,
    soundFrequency: "528hz",
    chakraSoundSyllable: "Youuuu",
    tags: ["pressure", "mental-toughness", "simulation"],
    isFreeAccess: false,
    sortOrder: 17,
  },
  {
    name: "Flow State Entry",
    slug: "flow-state-entry",
    stageRequired: 3,
    chakraFocus: ["crown", "third-eye"],
    element: "ether",
    durationMinutes: 15,
    targetBreathRate: 6,
    difficulty: "advanced",
    description: "Dual Crown-Third Eye protocol for entering flow state before competition or peak training.",
    steps: [
      "Sit in complete stillness. Environment controlled.",
      "Begin SAUMMM — Crown activation.",
      "After 5 minutes: add SONNN — Third Eye.",
      "Alternate: SAUMMM inhale, SONNN exhale.",
      "Feel awareness expand beyond the body.",
      "Do not force flow — allow it.",
      "End when you feel the shift. Not before.",
    ],
    inhaleSeconds: 6,
    holdAfterInhaleSeconds: 4,
    exhaleSeconds: 8,
    holdAfterExhaleSeconds: 2,
    soundFrequency: "963hz",
    chakraSoundSyllable: "SAUMMM",
    tags: ["flow-state", "peak-performance", "awareness"],
    isFreeAccess: false,
    sortOrder: 18,
  },

  // ─── STAGE 4: Integration & Mastery (6-8 → 4 or less bpm) ──────────────
  {
    name: "Demi-God Rate",
    slug: "demi-god-rate",
    stageRequired: 4,
    chakraFocus: ["crown"],
    element: "ether",
    durationMinutes: 30,
    targetBreathRate: 4,
    difficulty: "master",
    description: "The pinnacle Stage 4 protocol. Full elemental balance, 30-second holds, complete 7-chakra cycling. Above the inhale-exhale paradigm.",
    steps: [
      "Full elemental balance: Air → Fire → Water → Earth → Ether.",
      "Each element: minimum 5 breath cycles.",
      "30-second holds after each inhale — non-negotiable.",
      "Complete 7-chakra cycling: AHHH through SAUMMM.",
      "After minute 20: transcend the sound — breathe in silence.",
      "Maintain 4 breaths per minute or less.",
      "You are above the inhale-exhale paradigm now.",
    ],
    inhaleSeconds: 8,
    holdAfterInhaleSeconds: 30,
    exhaleSeconds: 10,
    holdAfterExhaleSeconds: 5,
    soundFrequency: "963hz",
    chakraSoundSyllable: "SAUMMM",
    tags: ["mastery", "elemental-balance", "transcendence"],
    isFreeAccess: false,
    sortOrder: 19,
  },
  {
    name: "Total Command",
    slug: "total-command",
    stageRequired: 4,
    chakraFocus: ["root", "sacral", "solar-plexus", "heart", "throat", "third-eye", "crown"],
    element: "ether",
    durationMinutes: 45,
    targetBreathRate: 3,
    difficulty: "master",
    description: "The ultimate protocol. All 7 chakras, all elements, 45 minutes. Body as projector. Heart as amplifier. Total command.",
    steps: [
      "Charge the pineal gland — first eye activation.",
      "Body becomes the projector — feel energy radiate.",
      "Heart amplifier: SoLLLL at maximum resonance.",
      "Iron blood, FAITH blood — feel the transformation.",
      "Cycle all 7 chakras with 30-second holds each.",
      "After minute 30: you are the lightest version of yourself.",
      "Maintain 3 breaths per minute for final 15 minutes.",
    ],
    inhaleSeconds: 10,
    holdAfterInhaleSeconds: 30,
    exhaleSeconds: 12,
    holdAfterExhaleSeconds: 8,
    soundFrequency: "963hz",
    chakraSoundSyllable: "SAUMMM",
    tags: ["total-command", "mastery", "all-elements"],
    isFreeAccess: false,
    sortOrder: 20,
  },
  {
    name: "Trance End",
    slug: "trance-end",
    stageRequired: 4,
    chakraFocus: ["crown", "third-eye"],
    element: "ether",
    durationMinutes: 20,
    targetBreathRate: 4,
    difficulty: "master",
    description: "Transcend duality. Crown-Third Eye fusion protocol. Water dissolves, stiff breaks, flexible yields.",
    steps: [
      "Close eyes. Charge the first eye.",
      "Use body as projector — feel the field expand.",
      "SAUMMM + SONNN simultaneously — feel the fusion.",
      "Transcend duality: inhale is exhale, silence is sound.",
      "Water dissolves all resistance.",
      "Stiff breaks. Flexible yields. Be water.",
      "End only when the boundary between self and breath disappears.",
    ],
    inhaleSeconds: 8,
    holdAfterInhaleSeconds: 20,
    exhaleSeconds: 12,
    holdAfterExhaleSeconds: 5,
    soundFrequency: "963hz",
    chakraSoundSyllable: "SAUMMM",
    tags: ["transcendence", "duality", "mastery"],
    isFreeAccess: false,
    sortOrder: 21,
  },
  {
    name: "Pineal Charge",
    slug: "pineal-charge",
    stageRequired: 4,
    chakraFocus: ["third-eye", "crown"],
    element: "ether",
    durationMinutes: 25,
    targetBreathRate: 4,
    difficulty: "master",
    description: "Direct pineal gland activation through sustained Third Eye-Crown resonance. The gateway to total awareness.",
    steps: [
      "Sit in complete darkness if possible.",
      "Focus all attention on the pineal — center of skull.",
      "SONNN on every exhale — feel the vibration build.",
      "After 10 minutes: add SAUMMM on inhale.",
      "Hold for 25 seconds — feel the charge accumulate.",
      "Do not release until the pressure is undeniable.",
      "Final 5 minutes: pure silence — the charge is complete.",
    ],
    inhaleSeconds: 8,
    holdAfterInhaleSeconds: 25,
    exhaleSeconds: 10,
    holdAfterExhaleSeconds: 5,
    soundFrequency: "852hz",
    chakraSoundSyllable: "SONNN",
    tags: ["pineal", "third-eye", "total-awareness"],
    isFreeAccess: false,
    sortOrder: 22,
  },
  {
    name: "Elemental Fusion",
    slug: "elemental-fusion",
    stageRequired: 4,
    chakraFocus: ["root", "sacral", "solar-plexus", "heart"],
    element: "ether",
    durationMinutes: 30,
    targetBreathRate: 4,
    difficulty: "master",
    description: "Fuse all four lower elements into unified Ether. The lower chakras become one continuous energy field.",
    steps: [
      "Begin with Earth — AHHH, root lock, full grounding.",
      "Transition to Water — Oooo, sacral flow.",
      "Fire — Youuuu, solar plexus ignition.",
      "Water — SoLLLL, heart expansion.",
      "Hold each element for 5 minutes minimum.",
      "In final 10 minutes: all four simultaneously.",
      "Feel them fuse into a single field — Ether.",
    ],
    inhaleSeconds: 8,
    holdAfterInhaleSeconds: 20,
    exhaleSeconds: 12,
    holdAfterExhaleSeconds: 5,
    soundFrequency: "528hz",
    chakraSoundSyllable: "SoLLLL",
    tags: ["elemental-fusion", "lower-chakras", "integration"],
    isFreeAccess: false,
    sortOrder: 23,
  },
  {
    name: "Zero Point",
    slug: "zero-point",
    stageRequired: 4,
    chakraFocus: ["crown"],
    element: "ether",
    durationMinutes: 20,
    targetBreathRate: 3,
    difficulty: "master",
    description: "The zero point. No technique. No effort. Pure breath mastery expressed as effortless being. For those who have completed all other protocols.",
    steps: [
      "No instructions. You know what to do.",
      "If you need instructions, return to Stage 3.",
      "Breathe at 3 per minute or less.",
      "SAUMMM if you need it. Silence if you do not.",
      "The protocol is complete when you decide it is.",
      "There is no end. There is no beginning.",
      "This is mastery.",
    ],
    inhaleSeconds: 10,
    holdAfterInhaleSeconds: 30,
    exhaleSeconds: 10,
    holdAfterExhaleSeconds: 10,
    soundFrequency: "963hz",
    chakraSoundSyllable: "SAUMMM",
    tags: ["mastery", "zero-point", "effortless"],
    isFreeAccess: false,
    sortOrder: 24,
  },
];

async function seed() {
  console.log("Seeding protocols...");
  for (const p of protocolData) {
    await db.insert(protocols).values(p).onDuplicateKeyUpdate({ set: { name: p.name } });
  }
  console.log(`Seeded ${protocolData.length} protocols.`);
  process.exit(0);
}

seed().catch((e) => {
  console.error(e);
  process.exit(1);
});
